# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

workspace 'QRCodeUIKitDemo.xcworkspace'
project 'QRCodeUIKitDemo.xcodeproj'

target 'QRCodeUIKitDemo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for QRCodeUIKitDemo
  pod 'QRCodeUIKit'
  pod 'YYWebImage'
end
