# Uncomment this line to define a global platform for your project
platform :ios, '10.0'

workspace 'QRCodeUIKitDemo.xcworkspace'
project 'QRCodeUIKitDemo.xcodeproj'

target 'QRCodeUIKitDemo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for QRCodeUIKitDemo
  pod 'QRCodeUIKit', :path => '../'
  pod 'YYWebImage'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 10.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
      end
    end
#    if target.name == "ZIPFoundation"
#      target.build_configurations.each do |config|
#        config.build_settings['SWIFT_VERSION'] = '5.0'
#      end
#    end
  end
  
  installer.pod_target_subprojects.flat_map { |p| p.targets }.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 10.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
      end
    end
  end
end
